spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market_test?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true #운영에서는 log로 찍어야함.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.apache.coyote.http11: info

#    springboot-dataSource-decorator

